import { fundamentalsText, clearinghouseText, theFedText, reposText } from "./texts";

export const introductoryTexts = {
  0: fundamentalsText.step1,
  1: fundamentalsText.step2,
  2: fundamentalsText.step3,
  3: fundamentalsText.step4,
  4: fundamentalsText.step5,
  5: fundamentalsText.step6,
  6: fundamentalsText.step7,
  7: clearinghouseText.step1,
  8: clearinghouseText.step2,
  9: clearinghouseText.step3,
  10: clearinghouseText.step4,
  11: clearinghouseText.step5,
  12: clearinghouseText.step6,
  13: clearinghouseText.step7,
  14: theFedText.step1,
  15: theFedText.step2,
  16: theFedText.step3,
  17: theFedText.step4,
  18: theFedText.step5,
  19: theFedText.step6,
  20: reposText.step1,
  21: reposText.step2,
  22: reposText.step3,
  23: reposText.step4,
  24: reposText.step5,
  25: reposText.step6,
  26: reposText.step6,
  27: reposText.step6,
  28: reposText.step6,
};
