export const lectureRoutes = {
  heading: true,
  path: "",
  routes: [
    {
      id: 0,
      title: "Fundamentals",
      path: "/lectures/fundamentals",
      routes: [
        {
          id: 0,
          title: "Introduction",
          path: "/fundamentals/introduction",
          lectureId: 0,
          keyTermsIds: [],
        },
        {
          id: 1,
          title: "Balance Sheets and Deposits",
          path: "/fundamentals/balance-sheets-and-deposits",
          lectureId: 0,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 2,
          title: "Deposit Transfers",
          path: "/fundamentals/deposit-transfers",
          lectureId: 0,
          keyTermsIds: [3, 4],
        },
        {
          id: 3,
          title: "Overdrafts",
          path: "/fundamentals/overdrafts",
          lectureId: 0,
          keyTermsIds: [5, 6],
        },
        {
          id: 4,
          title: "Loans",
          path: "/fundamentals/loans",
          lectureId: 0,
          keyTermsIds: [7, 8],
        },
        {
          id: 5,
          title: "Constraints",
          path: "/fundamentals/constraints",
          lectureId: 0,
          keyTermsIds: [9],
        },
        {
          id: 6,
          title: "Conclusion",
          path: "/fundamentals/conclusion",
          lectureId: 0,
          keyTermsIds: [],
        },
      ],
    },
    {
      id: 1,
      title: "Towards a Central Bank",
      path: "/lectures/towards-a-central-bank",
      routes: [
        {
          id: 7,
          title: "Introduction",
          path: "/towards-a-central-bank/introduction",
          lectureId: 1,
          keyTermsIds: [],
        },
        {
          id: 8,
          title: "One Big Bank",
          path: "/towards-a-central-bank/one-big-bank",
          lectureId: 1,
          keyTermsIds: [10, 11],
        },
        {
          id: 9,
          title: "Multiple Banks",
          path: "/towards-a-central-bank/multiple-banks",
          lectureId: 1,
          keyTermsIds: [12, 13],
        },
        {
          id: 10,
          title: "Correspondent Banking",
          path: "/towards-a-central-bank/correspondent-banking",
          lectureId: 1,
          keyTermsIds: [14, 15, 16, 17],
        },
        {
          id: 11,
          title: "The Clearing House",
          path: "/towards-a-central-bank/the-clearing-house",
          lectureId: 1,
          keyTermsIds: [18, 19, 20],
        },
        {
          id: 12,
          title: "Clearing House Loans",
          path: "/towards-a-central-bank/clearing-house-loans",
          lectureId: 1,
          keyTermsIds: [21],
        },
        {
          id: 13,
          title: "Conclusion",
          path: "/towards-a-central-bank/conclusion",
          lectureId: 1,
          keyTermsIds: [],
        },
      ],
    },
    {
      id: 2,
      title: "The Federal Reserve",
      path: "/lectures/the-federal-reserve",
      routes: [
        {
          id: 14,
          title: "Introduction",
          path: "/the-federal-reserve/introduction",
          lectureId: 2,
          keyTermsIds: [],
        },
        {
          id: 15,
          title: "Daylight Overdrafts",
          path: "/the-federal-reserve/daylight-overdrafts",
          lectureId: 2,
          keyTermsIds: [22, 23, 24],
        },
        {
          id: 16,
          title: "The Fed Funds Market",
          path: "/the-federal-reserve/the-fed-funds-market",
          lectureId: 2,
          keyTermsIds: [25, 26],
        },
        {
          id: 17,
          title: "Funding a Mortgage",
          path: "/the-federal-reserve/funding-a-mortgage",
          lectureId: 2,
          keyTermsIds: [27, 28],
        },
        {
          id: 18,
          title: "Fed Funds Rate: Effective",
          path: "/the-federal-reserve/fed-funds-rate-1",
          lectureId: 2,
          keyTermsIds: [29, 30],
        },
        {
          id: 19,
          title: "Fed Funds Rate: Target",
          path: "/the-federal-reserve/fed-funds-rate-2",
          lectureId: 2,
          keyTermsIds: [31, 32],
        },
      ],
    },
    // {
    //   id: 3,
    //   title: "Repos",
    //   path: "/lectures/repos",
    //   routes: [
    //     {
    //       id: 0,
    //       title: "Introduction",
    //       path: "/repos/introduction",
    //       lectureId: 3,
    //       keyTermsIds: [],
    //     },
    //     {
    //       id: 1,
    //       title: "Repo in Balance Sheets",
    //       path: "/repos/repo-in-balance-sheets",
    //       lectureId: 3,
    //       keyTermsIds: [3, 1, 2],
    //     },
    //     {
    //       id: 2,
    //       title: "Comparison with Fed Funds",
    //       path: "/repos/comparison-with-fed-funds",
    //       lectureId: 3,
    //       keyTermsIds: [3, 4],
    //     },
    //     {
    //       id: 3,
    //       title: "Legal Construction of Repo",
    //       path: "/repos/legal-construction-of-repo",
    //       lectureId: 3,
    //       keyTermsIds: [5, 6],
    //     },
    //     {
    //       id: 4,
    //       title: "Security Dealers",
    //       path: "/repos/security-dealers",
    //       lectureId: 3,
    //       keyTermsIds: [7, 8],
    //     },
    //     {
    //       id: 5,
    //       title: "Repo and the Fed",
    //       path: "/repos/repo-and-the-fed",
    //       lectureId: 3,
    //       keyTermsIds: [9],
    //     },
    //     {
    //       id: 6,
    //       title: "Interest Rate Spreads",
    //       path: "/repos/interest-rate-spreads",
    //       lectureId: 3,
    //       keyTermsIds: [],
    //     },
    //   ],
    // },
    // {
    //   id: 4,
    //   title: "Eurodollars",
    //   path: "/lectures/eurodollars",
    //   routes: [
    //     {
    //       id: 0,
    //       title: "Introduction",
    //       path: "/eurodollars/introduction",
    //       lectureId: 4,
    //       keyTermsIds: [],
    //     },
    //     {
    //       id: 1,
    //       title: "Eurodollar Markets",
    //       path: "/eurodollars/eurodollar-markets",
    //       lectureId: 4,
    //       keyTermsIds: [3, 1, 2],
    //     },
    //     {
    //       id: 2,
    //       title: "Liquidity and Eurodollars",
    //       path: "/eurodollars/liquidity-and-eurodollars",
    //       lectureId: 4,
    //       keyTermsIds: [3, 4],
    //     },
    //     {
    //       id: 3,
    //       title: "Forward Rate Markets",
    //       path: "/eurodollars/forward-rate-markets",
    //       lectureId: 4,
    //       keyTermsIds: [5, 6],
    //     },
    //     {
    //       id: 4,
    //       title: "Forward Parity: Interest Rates",
    //       path: "/eurodollars/forward-parity-interest-rates",
    //       lectureId: 4,
    //       keyTermsIds: [7, 8],
    //     },
    //     {
    //       id: 5,
    //       title: "Forward Parity: Exchange Rates",
    //       path: "/eurodollars/forward-parity-exchange-rates",
    //       lectureId: 4,
    //       keyTermsIds: [9],
    //     },
    //     {
    //       id: 6,
    //       title: "Expected Spot Rates",
    //       path: "/eurodollars/expected-spot-rates",
    //       lectureId: 4,
    //       keyTermsIds: [],
    //     },
    //   ],
    // },
    // {
    //   id: 5,
    //   title: "City of London",
    //   path: "/lectures/city-of-london",
    //   routes: [
    //     {
    //       id: 3,
    //       title: "Introduction",
    //       path: "/city-of-london/introduction",
    //       lectureId: 5,
    //       keyTermsIds: [],
    //     },
    //     {
    //       id: 1,
    //       title: "Wholesale Money Market",
    //       path: "/city-of-london/wholesale-money-market",
    //       lectureId: 5,
    //       keyTermsIds: [3, 1, 2],
    //     },
    //     {
    //       id: 2,
    //       title: "Deposits and Acceptances",
    //       path: "/city-of-london/deposit-and-acceptances",
    //       lectureId: 5,
    //       keyTermsIds: [3, 4],
    //     },
    //     {
    //       id: 3,
    //       title: "Discounts and Rediscounts",
    //       path: "/city-of-london/discounts-and-rediscounts",
    //       lectureId: 5,
    //       keyTermsIds: [5, 6],
    //     },
    //     {
    //       id: 4,
    //       title: "Market Rate of Interest",
    //       path: "/city-of-london/market-rate-of-interest",
    //       lectureId: 5,
    //       keyTermsIds: [7, 8],
    //     },
    //     {
    //       id: 5,
    //       title: "Central Bank and Bank Rate",
    //       path: "/city-of-london/central-bank-and-bank-rate",
    //       lectureId: 5,
    //       keyTermsIds: [9],
    //     },
    //     {
    //       id: 6,
    //       title: "The Bagehot Rule",
    //       path: "/city-of-london/the-bagehot-rule",
    //       lectureId: 5,
    //       keyTermsIds: [],
    //     },
    //   ],
    // },
  ],
};
